width = 17
height = 12.0
a = width // 2
b = width / 2.0
c = height / 3
d = 1 + 2 * 5
print('width // 2 =', a, '->', type(a))
print('width / 2.0 =', b, '->', type(b))
print('height / 3 =', c, '->', type(c))
print('1 + 2 * 5 =', d, '->', type(d))